spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/workly_db?sslmode=disable
    username: workly_user
    password: workly_pass

workly:
  security:
    secret: 'SecretForJWT'
    expiration-time: 1800000
  swagger:
    host: 'localhost:8080'
    protocol: 'http'
